# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    wordpress_service.yaml                             :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nelisabe <nelisabe@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/22 17:53:16 by nelisabe          #+#    #+#              #
#    Updated: 2020/12/22 20:30:20 by nelisabe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared #enable selective IP sharing (enable single ip)
  name: wordpress-service
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
      - port: 5050
        name: wordpress-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-pod
        image: wordpress_image
        imagePullPolicy: Never
        ports:
            - containerPort: 5050
