# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    telegraf_service.yaml                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nelisabe <nelisabe@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/26 18:56:57 by nelisabe          #+#    #+#              #
#    Updated: 2020/12/30 14:11:16 by nelisabe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
spec:
  selector:
    app: telegraf
  ports:
      - port: 8086
        name: telegraf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      containers:
      - name: telegraf
        image: telegraf_image
        imagePullPolicy: Never
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        ports:
            - containerPort: 8086
