# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps_service.yaml                                  :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nelisabe <nelisabe@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/17 14:39:10 by nelisabe          #+#    #+#              #
#    Updated: 2020/12/29 20:05:00 by nelisabe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared #enable selective IP sharing (enable single ip)
  name: ftps-service
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
      - port: 21
        name: ftp-control-stream #input only
        protocol: TCP
      - port: 20
        name: ftp-data-active-stream
        protocol: TCP
      - port: 10000
        name: ftp-data-passive-stream
        protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps-pod
        image: ftps_image
        imagePullPolicy: Never
        ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 10000
