# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    grafana_service.yaml                               :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nelisabe <nelisabe@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/29 11:40:04 by nelisabe          #+#    #+#              #
#    Updated: 2020/12/29 15:39:53 by nelisabe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared #enable selective IP sharing (enable single ip)
  name: grafana-service
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
      - port: 3000
        name: grafana-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-pod
        image: grafana_image
        imagePullPolicy: Never
        ports:
            - containerPort: 3000
