# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx_service.yaml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nelisabe <nelisabe@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/17 14:39:03 by nelisabe          #+#    #+#              #
#    Updated: 2020/12/30 14:10:25 by nelisabe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared #enable selective IP sharing (enable single ip)
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
      - port: 22
        name: ssh
        protocol: TCP
      - port: 80
        name: http
        protocol: TCP
      - port: 443
        name: https
        protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx_image
        imagePullPolicy: Never
        ports:
            - containerPort: 22
            - containerPort: 80
            - containerPort: 443
