# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    pma_service.yaml                                   :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nelisabe <nelisabe@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/22 17:53:16 by nelisabe          #+#    #+#              #
#    Updated: 2020/12/30 14:11:04 by nelisabe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared #enable selective IP sharing (enable single ip)
  name: pma-service
spec:
  selector:
    app: pma
  type: LoadBalancer
  ports:
      - port: 5000
        name: pma-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
  labels:
    app: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: phpmyadmin
        image: pma_image
        imagePullPolicy: Never
        ports:
            - containerPort: 5000
