# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    my_sql_service.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nelisabe <nelisabe@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/18 17:22:16 by nelisabe          #+#    #+#              #
#    Updated: 2020/12/18 17:58:36 by nelisabe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
      - port: 3306 # mysql defalt port
        name: mysql